server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/novel?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  type-aliases-package: com.suny.spider.novel.web.entitys
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: com/suny/web/mapper/*.xml

